.PHONY: clean clean_all fmt lint check release-tag

PROJ_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

EXTENSION_NAME=duckstream

# duckdb-rs relies on the unstable C API, so this must be 1.
# NOTE: this pins the produced binary to exactly TARGET_DUCKDB_VERSION;
# there is no forward compatibility across DuckDB releases.
USE_UNSTABLE_C_API=1

# Target DuckDB version. Must match the DuckDB version encoded by the duckdb
# crate (see Cargo.toml) and the extension-ci-tools submodule branch.
TARGET_DUCKDB_VERSION=v1.5.4

all: configure debug

# Include makefiles from DuckDB's extension-ci-tools (Rust C-API extension flow)
include extension-ci-tools/makefiles/c_api_extensions/base.Makefile
include extension-ci-tools/makefiles/c_api_extensions/rust.Makefile

configure: venv platform extension_version

debug: build_extension_library_debug build_extension_with_metadata_debug
release: build_extension_library_release build_extension_with_metadata_release

test: test_debug
test_debug: test_extension_debug
test_release: test_extension_release

clean: clean_build clean_rust
clean_all: clean_configure clean

fmt: ## Format all Rust sources
	cargo fmt --all

lint: ## Check formatting and run clippy with warnings denied
	cargo fmt --all -- --check
	cargo clippy --all-targets -- -D warnings

check: lint ## Run lint + unit tests (fast pre-commit gate; no extension build)
	cargo test --lib

# Read the crate version from Cargo.toml (single source of truth), tag it, and
# push. The Release workflow (triggered by the v* tag) verifies the tag matches
# this version and cuts the GitHub Release, with notes generated by git-cliff.
# MainDistributionPipeline.yml builds the cross-platform binaries on the same
# tag. (Named release-tag, not release: `release` already builds the optimized
# extension above.)
release-tag: ## Tag and push a release (reads version from Cargo.toml)
	@VERSION=$$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version'); \
	TAG="v$$VERSION"; \
	if git rev-parse "$$TAG" >/dev/null 2>&1; then \
		printf "\033[31mError: tag $$TAG already exists\033[0m\n"; exit 1; \
	fi; \
	printf "\033[36mCreating release $$TAG\033[0m\n"; \
	git tag -a "$$TAG" -m "release: $$TAG"; \
	git push origin "$$TAG"; \
	printf "\033[32mPushed $$TAG - Release workflow will cut the GitHub Release\033[0m\n"
